### PR TITLE
remove this disgusting project, it is in violation of myself and ever…

### PR DESCRIPTION
**Pull request by ChachyDev**
…ything else

### CODE REVIEW

**Review by proudmuslim-dev — APPROVED** [review]
LGTM :+1:

**Review by xcfrg — CHANGES_REQUESTED** [review]
deez nuts

**Review by dreamhopping — CHANGES_REQUESTED** [review]
this is not good for the project it   is against the idea

**Review by MicrocontrollersDev — CHANGES_REQUESTED** [review]
Make a new file called README.md and add:

# chachy-alternatives
fuck you chachy


- Systemless - better in every single way
- Bruno - havent seen this guy in a good year but still a better alternative
- Noctember - plays valorant
- Conor - conor

# things not to do
- don't be chachy
- - british

# Credits
- Chachy

**Comment by ChachyDev** [comment]
> Make a new file called README.md and add:
> 
> 
> 
> # chachy-alternatives
> 
> fuck you chachy
> 
> 
> 
> 
> 
> - Systemless - better in every single way
> 
> - Bruno - havent seen this guy in a good year but still a better alternative
> 
> - Noctember - plays valorant
> 
> - Conor - conor
> 
> 
> 
> # things not to do
> 
> - don't be chachy
> 
> - - british
> 
> 
> 
> # Credits
> 
> - Chachy

no

**Comment by proudmuslim-dev** [comment]
Ready for merging!

**Review by MicrocontrollersDev — APPROVED** [review]

**Comment by MicrocontrollersDev** [comment]
please fix conflicts

**Pull request closed without merging**
